# Generated by Django 5.1.5 on 2025-02-05 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='RecNo',
            new_name='RefferedBy',
        ),
    ]
