# Generated by Django 5.1.5 on 2025-01-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='RegistrationId',
            field=models.CharField(max_length=100),
        ),
    ]
