# Generated by Django 5.1 on 2025-02-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_alter_patient_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='RefferedBy',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
