# Generated by Django 5.1 on 2025-02-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_alter_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='ConsultationFee',
        ),
    ]
