# Generated by Django 5.1.5 on 2025-01-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_alter_patient_age_alter_patient_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ConsultationFee',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Doctor',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Email',
            field=models.EmailField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='FeeType',
            field=models.CharField(blank=True, default=1, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='FirstName',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Gender',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='LastName',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PhoneNumber',
            field=models.CharField(default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='RegistrationId',
            field=models.CharField(default=1, max_length=100, unique=True),
        ),
    ]
