# Generated by Django 5.1.5 on 2025-02-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_alter_patient_refferedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='PhoneNumber',
            field=models.IntegerField(null=True),
        ),
    ]
