# Generated by Django 5.1.5 on 2025-01-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_alter_patient_consultationfee_alter_patient_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Age',
            field=models.IntegerField(),
        ),
    ]
