# Generated by Django 5.1.5 on 2025-01-31 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_alter_patient_age'),
        ('Patient', '0005_alter_patient_age'),
    ]

    operations = [
    ]
