# Generated by Django 5.1.5 on 2025-01-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0006_merge_0003_alter_patient_age_0005_alter_patient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='RegistrationId',
            field=models.AutoField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
