# Generated by Django 5.1.5 on 2025-01-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_remove_patient_id_alter_patient_registrationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='RegistrationId',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
