# Generated by Django 5.1.5 on 2025-02-13 11:48

import register.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp_code', models.CharField(default=register.models.generate_otp, max_length=6)),
                ('otp_expires_at', models.DateTimeField()),
            ],
        ),
    ]
