# Generated by Django 5.1.5 on 2025-02-07 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientappointment',
            old_name='doc',
            new_name='doctor',
        ),
    ]
