# Generated by Django 5.1.5 on 2025-01-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappointment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Accept'), (2, 'Waiting')], default=2),
        ),
    ]
