# Generated by Django 5.1.5 on 2025-01-31 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientappointment',
            name='RegistrationId',
        ),
    ]
