# Generated by Django 5.1.5 on 2025-02-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.IntegerField(choices=[(0, 'Canceled'), (1, 'Done'), (2, 'Engaged'), (3, 'Waiting'), (4, 'Scheduled')], default=4),
        ),
    ]
