# Generated by Django 5.1.3 on 2025-02-11 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='FirstName',
            new_name='firstname',
        ),
    ]
