# Generated by Django 5.1.5 on 2025-02-10 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_rename_doc_patientappointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.doctor'),
        ),
    ]
