# Generated by Django 5.1.5 on 2025-01-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_patientappointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappointment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Decline'), (1, 'Accept'), (2, 'Waiting')], default=2),
        ),
    ]
