# Generated by Django 5.1.3 on 2025-02-11 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_rename_firstname_doctor_firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='PhoneNumber',
        ),
    ]
