# Generated by Django 5.1.5 on 2025-02-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_patientappointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.IntegerField(choices=[('Canceled', 'Canceled'), ('Done', 'Done'), ('Engaged', 'Engaged'), ('Waiting', 'Waiting'), ('Scheduled', 'Scheduled')], default='Scheduled'),
        ),
    ]
