# Generated by Django 5.1.5 on 2025-01-30 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
        ('appointment', '0003_alter_patientappointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Patient.patient'),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
