# Generated by Django 5.1.5 on 2025-01-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointment_patient_delete_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointment',
            name='RegistrationId',
            field=models.CharField(default=1, max_length=100, unique=True),
        ),
    ]
