# Generated by Django 5.1.5 on 2025-02-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Done', 'Done'), ('Engaged', 'Engaged'), ('Waiting', 'Waiting'), ('Scheduled', 'Scheduled')], default='Scheduled', max_length=50),
        ),
    ]
