# Generated by Django 5.1.5 on 2025-01-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_patientappointment_registrationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappointment',
            name='RegistrationId',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
