# Generated by Django 5.1.5 on 2025-02-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_alter_appointments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappointment',
            name='status',
            field=models.CharField(choices=[('Decline', 'Decline'), ('Accept', 'Accept'), ('Waiting', 'Waiting')], default='Waiting', max_length=50),
        ),
    ]
